app = "casper-mod-bot"
primary_region = "yul"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  PORT = "8001"
